apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::123456789:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-xxxxxxx
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::123456789:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: 2020-05-18T23:51:24Z
  name: aws-auth
  namespace: kube-system
  resourceVersion: "14775"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ************************************
